### ISSUE TITLE
sınıf 

### ISSUE THREAD

**Issue by VB10** [yakupemeksiz/my_favorite_books#5]
https://github.com/yakupemeksiz/my_favorite_books/blob/dc36b4ab4da9e2cba073cb150119632b6184dcfc/lib/bootstrap.dart#L16

ben genel olarak bir methodun veriable veya herhangi bir şeyin dışarıda kalmasına veya doğrudan kodla erişilmesini çok sevmiyorum ondan burada sınıf içine koyabilir , part partof da dahil ederek bu methdo sınıfı sadece bir noktaya özel kılabiliriz

**Comment by yakupemeksiz** [comment]
@VB10 yorumunuz için teşekkürler hocam, fixledim 🙏
